CREATE TABLE IF NOT EXISTS PRODUCT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    QUANTITY INT DEFAULT 0,
    PRICE DOUBLE DEFAULT 0,
    ID_CATEGORY BIGINT,
    ID_IMAGE BIGINT,
    FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID),
    FOREIGN KEY (ID_IMAGE) REFERENCES IMAGE(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;